### ISSUE TITLE
use indentation from response rather than rstudioapi?

### ISSUE THREAD

**Issue by simonpcouch** [simonpcouch/pal#9]
Should look into whether models are getting indentation right already.

**Comment by Koalha** [comment]
Thanks for the quick reply @simonpcouch! Seems I should have done some more testing related to the backticks. It's actually good to hear that the problem is probably related to the specific model I was using (and maybe to its interaction with ollama), since that means I can just focus on finding a model that plays better with pal.

**Comment by simonpcouch** [comment]
Hey @Koalha, you were right! The `sub()` call in this line was the culprit:

https://github.com/simonpcouch/pal/blob/f3455dd11978fb9a19d2b530755086d7776db49c/R/rstudioapi.R#L153

I don't remember why I initially introduced that line in the first hacky hours of the package, and removing it seems to resolve the problem. Qwen 2.5 seems to chunk up tokens in a way that triggers this bug more often than other models. From Qwen, I see newlines included in chunks like `":\n\n"`, `"\n"`, or `"(\n"`. From Claude, I see newlines interspersed like `" \n   when including arguments\", call"`, `"\n"`, or `"::cli_abort(\n  \"here's a"`. As the function is now written, though, I don't see any reason we need to strip trailing newlines per-token. Removing now.

Going to go ahead and close this issue, too, as I do think we'll continue to rely on the rstudio API to reformat.
